### ISSUE TITLE
Add npx command

### ISSUE THREAD

**Issue by scriptex** [three11/react-template-ts#1125]

**Comment by NikolovMartin** [comment]
create-awesome-react-ts-app

**Comment by scriptex** [comment]
`bootstrap-react-app`

**Comment by NikolovMartin** [comment]
мойто ме кефи повече :)

**Comment by scriptex** [comment]
@NikolovMartin  `create-awesome-react-app` ????

**Comment by NikolovMartin** [comment]
ами да, аз включих тс че да се знае че е TS

**Comment by scriptex** [comment]
хората, които са решили да го ползват, би трябвало да знаят, че е TS
