### ISSUE TITLE
Use ESLint instead of TSLint

### ISSUE THREAD

**Issue by alpanayotov** [three11/react-template-ts#484]
As per https://github.com/palantir/tslint/issues/4534 TSLinst is being deprecated. Migration to ESLint should be considered.

**Comment by scriptex** [comment]
https://github.com/typescript-eslint/tslint-to-eslint-config

**Comment by scriptex** [comment]
WIP in #538

**Comment by scriptex** [comment]
Done in ffb23ca0c8a574aa39f67d776bfc75c3ace7f995
